name: conference_system
description: "Design and implement a system that allows users to view, reserve, and pay for conference or meeting rooms online."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
   uses-material-design: true

   assets:
     - assets/images/hamayesh1.jpg
     - assets/images/hamayesh2.jpg
     - assets/images/default_avatar.png

   fonts:
     - family: Farsi
       fonts:
         - asset: assets/fonts/B Roya Bold.ttf
           style: normal
           weight: 700
