name: conference_system
description: "Design and implement a system that allows users to view, reserve, and pay for conference or meeting rooms online."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.4
  collection: ^1.17.0

  #local data_base
  http: ^0.13.5

  flutter_bloc: ^9.0.0

  equatable: ^2.0.7

  cupertino_icons: ^1.0.8

  shared_preferences: ^2.2.2

  translator: ^0.1.7
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  file_picker: ^10.2.0
  shamsi_date: ^1.1.0
  persian_datetime_picker: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
   uses-material-design: true

   assets:
     - assets/images/hamayesh1.jpg
     - assets/images/hamayesh2.jpg
     - assets/images/default_avatar.png

   fonts:
     - family: Farsi
       fonts:
         - asset: assets/fonts/B Yekan.ttf
           style: normal
           weight: 700
